# manage server configuration
server:
  servlet:
    contextPath: "/estime/v1"
    
# manage spring configuration
spring:
  application:
    name: "estime-backend"
  profiles:
    active: "--ENVIRONMENT--"
  security:
    oauth2:
      client:
        provider:
          oauth-pole-emploi:
            token-uri: "--PE_CONNECT_TOKEN_URI--"
            user-info-uri: "--PE_CONNECT_USER_INFO_URI--"
        registration:
          estime:
            authorization-grant-type: authorization_code
            client-id: "--PE_CONNECT_CLIENT_ID--"
            client-secret: "--PE_CONNECT_CLIENT_SECRET--"
            provider: oauth-pole-emploi
      resourceserver:
        jwt:
          jwk-set-uri: "--PE_CONNECT_JWK_SET_URI--"
          issuer-uri: "--PE_CONNECT_ISSUER_URI--"

#manage monitoring endpoints
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
        
#poleemploi.io
poleemploiio-uri : "--POLE_EMPLOI_IO_URI--"
  
#open fisca
openfisca-api-uri: "https://estime.beta.pole-emploi.fr/calculate"